version: '3.5'
services:
  web:
    build: .
    networks:
      - bravo
    ports:
     - "8100:80"
    volumes:
     - /home/ales/bravo_browser/bravo/data:/data
  mongo:
    image: "mongo:3.4"
    volumes:
     - /home/ales/bravo_browser/bravo/data/mongo/data/db:/data/db
    networks:
      - bravo
    command: --wiredTigerCacheSizeGB 30.0
networks:
  bravo:
    name: bravoWebApp
