version: '3'
services:
  web:
    build: .
    ports:
     - "7778:80"
    volumes:
     - /var/bravo:/var/bravo
    environment:
     - BRAVO_CONFIG_FILE=/var/bravo/config/config.py
  mongo:
    image: "mongo:3.4"
    volumes:
     - /var/bravo/mongo/db:/data/db
    
